active-plan: sandbox
otp:
  enabled: false
  evolution:
    host: https://evo.example.com
    api-key: null
    instance: otp-instance
security:
  message-filter: false
web-search:
  provider: brave
menu:
  contexts:
    main:
      workflows: false
      inbox: false
      aprovacoes: false
      analytics: false
      ratings: false
      seguranca: false
      conformidade: false
      fleet: false
      opentelemetry: false
    agent:
      knowledge: true
      versoes: false
      quotas: false
      conformidade: false
      circuit_breaker: false
      avaliacao: false
      qualidade: false
      benchmarks: false
infrastructure:
  ngrok:
    authtoken: ENC(MjEJ5S4DxMJbIEsaUnmokNgeAdZUYsrwXz4/enkbpHY5MfH1xxpxUz4OuVqGBpFL24EOMhvGYfb0Zg+DfXsptYkhlZ4OgTkPWDZNR9s=)
    domain: nonporphyritic-microcrystalline-kenya.ngrok-free.dev
    enabled: true
  whisper:
    model: small
    compute-type: int8
providers:
  openrouter:
    api_key: ENC(XZQE0AGQn/n1cSThY9u1yCSzLfacDLWyiG+e36qG5Gd3J4NHBn/j/T8FUHFc3jz9Rd+7gifT847otFyU1CKYxXgU73Kc0i6uLMUJ/VBo+/+/qxTIuxDnD8jWxt77c67Y1Z096Rk=)
  openai:
    api_key: ENC(w8DS3xTfzZTAicGFvifqD7pR0Thi7x6IHRxdk4BIMF2q+EHHbqSyCUANai8KldNeBGVmaczbCWcpMNSyvKO31zPrgk7HqXfIjNyttj2Z+PEZDMo+U6ILL/5YvpVAf3FT0PTGF7EFKvHtaaqPjKdLLN5mjDwM1JHYj3nfBiI4S2HRceHSGJnLissG/gPkpsuKnzSkuaoGAk7KRCbv0q2EHotXbP0EZmC+O1fU6Nyu33QjCVsTHqnnC3J2lep9nLaS)
  brave:
    api_key: ENC(3Q7phj2tQq6IaOkbV2D14IqoEc8RlDo/3ndefOd4m3+UqUcRNsMmk2Bopq/v9suTIsKTfSOMqK+g+wM=)
  groq:
    api_key: ENC(qu4Sy5vOTLBxnRIpzHJWLIQ+LzFP1o387k8qTHAQTKha8d8HvQLBlCLr+k3oETDgDUKkXDCDQYePioyIySyeSH4zr3xFdFXazQnGBe/w0BgOBt9W)
